[package]
name = "rb_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }

[[bin]]
name = "rb_cli"
path = "bin/cli.rs"
